project:
  type: website
  output-dir: docs

website:
  title: "Puja's Website"
  navbar:
    left: 
      - href: Index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: blog.qmd
        text: Projects

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    toc-depth: 2
    number-sections: true
    self-contained: true
    css: styles.css



